networks:
  my_network:
    driver: bridge

services:

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: crud1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: blackangel
    ports:
      - "5434:5432"
    networks:
      - my_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2G
      replicas: 1
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -u postgres -d crud1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  backend:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env 
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - my_network
    command: >
      sh -c "sleep 100 && python manage.py migrate python && manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
       - /home/roque/OneDrive/Рабочий стол/dj-homeworks_old/3.2-crud/stocks_products/static:/static
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - my_network
    

